// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALYheFFcOMMBJP1YD2bnTABTCZDZ0GadQ',
    appId: '1:362220553943:web:c812711dc8e66d7f1b5292',
    messagingSenderId: '362220553943',
    projectId: 'perizinan-santri',
    authDomain: 'perizinan-santri.firebaseapp.com',
    storageBucket: 'perizinan-santri.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwejXF1q2xfOAoz__fmtqiOeDHJYqXG4E',
    appId: '1:362220553943:android:4b743a9c56f5c0f71b5292',
    messagingSenderId: '362220553943',
    projectId: 'perizinan-santri',
    storageBucket: 'perizinan-santri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnU9IARjL-qYZGYeiYJAlfCuRWUOxht9w',
    appId: '1:362220553943:ios:949a2fbb941cf2761b5292',
    messagingSenderId: '362220553943',
    projectId: 'perizinan-santri',
    storageBucket: 'perizinan-santri.firebasestorage.app',
    iosBundleId: 'com.example.perizinanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnU9IARjL-qYZGYeiYJAlfCuRWUOxht9w',
    appId: '1:362220553943:ios:949a2fbb941cf2761b5292',
    messagingSenderId: '362220553943',
    projectId: 'perizinan-santri',
    storageBucket: 'perizinan-santri.firebasestorage.app',
    iosBundleId: 'com.example.perizinanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALYheFEoOMMBJPlYD2bnTABTCZDZ06ad0',
    appId: '1:362220553943:web:180e464d4ba1ac691b5292',
    messagingSenderId: '362220553943',
    projectId: 'perizinan-santri',
    authDomain: 'perizinan-santri.firebaseapp.com',
    storageBucket: 'perizinan-santri.firebasestorage.app',
  );
}
